# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63cf755a8c7f0ae18fe290b615ac63442ddae39c78108463f612ac6cdadbf54e18a4b52d1e085a6c2cb909c35ce6782bddfd2d560fc6a5e475426ee892573862

test:
  secret_key_base: 7dae4e99c1cc035b667e616ba444bfde7022328052cef9b8d364d79cba2e9007ae73676d8eff49981a9902ab9781de61592d67ed14490bf7582e4a3d1b1893c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
